### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [Molmed/summary-report-development#16]
Hey @mmbioinfo - I am seeing that you are making requests to use this container on Singularity Hub! Normally that's great but we are currently still testing, so I need to ask you to refrain from doing this until the server is officially open again. Thanks!

**Comment by matrulda** [comment]
Oh my bad @vsoch , I wasn't aware of a maintenance, I just thought the site was temporarily down. Will give you a break! :)

**Comment by vsoch** [comment]
Thanks! It's been quite a few weeks, haha. Things are currently looking good, but I am in the process of doing more detailed testing until it's officially open again. Here's the whole thread for a bit of history:

https://twitter.com/vsoch/status/1146801275843072001

I'll update there with more progress! Thanks for your speedy response.

**Comment by matrulda** [comment]
Wow, totally missed this. Haven't been working on this project for a while. Good luck with the testing and thanks for the information!
